---
- hosts: mysql
  gather_facts: no
  vars_files:
  - "{{ playbook_dir }}/vars/ehr_test.yaml"

  tasks:
  - name: mysql 创建用户
    mysql_user:
      name: "{{ item.key }}"
      password: "{{ item.value.password }}"
      priv: "{{ item.value.priv }}"
      host: "{{ item.value.host }}"
      state: present
#      login_unix_socket: "{{ mysql_login_info.socket }}"
      login_host: "{{ mysql_login_info.host }}"
      login_user: "{{ mysql_login_info.user }}"
      login_password: "{{ mysql_login_info.password }}"
    loop: "{{ mysql_create_user | dict2items }}"
#    no_log: true